# Default target
all: player1 player2 player3 player4 player5 player6 player7 player8

# Rule to run the Go file
player1:
	go run cpu.go

player2:
	go run cpu.go

player3:
	go run cpu.go

player4:
	go run cpu.go

player5:
	go run cpu.go

player6:
	go run cpu.go

player7:
	go run cpu.go
	
player8:
	go run cpu.go

.PHONY: all
